### ISSUE TITLE
If a API lookup fails to slack bot crashes

### ISSUE THREAD

**Issue by Tylarb** [Tylarb/Acorn-Project#6]
Issue happens if incorrect format is typed when tagging - example : @bot tag BOSH bosh

~~~
   2018-07-19T13:21:54.03-0400 [APP/PROC/WEB/0] OUT time="2018-07-19T17:21:54Z" level=error msg="API call to get chan info failed" id=bosh
   2018-07-19T13:21:54.03-0400 [APP/PROC/WEB/0] OUT time="2018-07-19T17:21:54Z" level=panic msg=channel_not_found
   2018-07-19T13:21:54.03-0400 [APP/PROC/WEB/0] ERR panic: (*logrus.Entry) (0x55a0270dfd80,0xc4202382d0)
   2018-07-19T13:21:54.03-0400 [APP/PROC/WEB/0] ERR goroutine 1 [running]:
   2018-07-19T13:21:54.03-0400 [APP/PROC/WEB/0] ERR supportBot/vendor/github.com/sirupsen/logrus.Entry.log(0xc420165720, 0xc4201de930, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x55a000000000, ...)
   2018-07-19T13:21:54.03-0400 [APP/PROC/WEB/0] ERR 	/tmp/gobuildpack.gopath548464076/.go/src/supportBot/vendor/github.com/sirupsen/logrus/entry.go:112 +0x256
   2018-07-19T13:21:54.03-0400 [APP/PROC/WEB/0] ERR supportBot/vendor/github.com/sirupsen/logrus.(*Entry).Panic(0xc420238190, 0xc420777468, 0x1, 0x1)
   2018-07-19T13:21:54.03-0400 [APP/PROC/WEB/0] ERR 	/tmp/gobuildpack.gopath548464076/.go/src/supportBot/vendor/github.com/sirupsen/logrus/entry.go:182 +0xac
   2018-07-19T13:21:54.03-0400 [APP/PROC/WEB/0] ERR supportBot/vendor/github.com/sirupsen/logrus.(*Logger).Panic(0xc420165720, 0xc420777468, 0x1, 0x1)
   2018-07-19T13:21:54.03-0400 [APP/PROC/WEB/0] ERR 	/tmp/gobuildpack.gopath548464076/.go/src/supportBot/vendor/github.com/sirupsen/logrus/logger.go:236 +0x6f
   2018-07-19T13:21:54.03-0400 [APP/PROC/WEB/0] ERR supportBot/vendor/github.com/sirupsen/logrus.Panic(0xc420777468, 0x1, 0x1)
   2018-07-19T13:21:54.03-0400 [APP/PROC/WEB/0] ERR 	/tmp/gobuildpack.gopath548464076/.go/src/supportBot/vendor/github.com/sirupsen/logrus/exported.go:107 +0x4d
   2018-07-19T13:21:54.03-0400 [APP/PROC/WEB/0] ERR main.getChanName(0xc420442371, 0x4, 0xc4206c0601, 0x0)
   2018-07-19T13:21:54.03-0400 [APP/PROC/WEB/0] ERR 	/tmp/gobuildpack.gopath548464076/.go/src/supportBot/slackMisc.go:88 +0x177
   2018-07-19T13:21:54.04-0400 [APP/PROC/WEB/0] ERR main.AddTag(0x0, 0x0, 0xc420edb1f8, 0x4, 0x0, 0x0, 0xc420442371, 0x4, 0x0, 0x0, ...)
   2018-07-19T13:21:54.04-0400 [APP/PROC/WEB/0] ERR 	/tmp/gobuildpack.gopath548464076/.go/src/supportBot/dbopts.go:149 +0xbb3
   2018-07-19T13:21:54.04-0400 [APP/PROC/WEB/0] ERR main.(*TagCache).Add(0xc4201465f0, 0x0, 0x0, 0xc420edb1f8, 0x4, 0x0, 0x0, 0xc420442371, 0x4, 0x0, ...)
   2018-07-19T13:21:54.04-0400 [APP/PROC/WEB/0] ERR 	/tmp/gobuildpack.gopath548464076/.go/src/supportBot/tagCache.go:99 +0x389
   2018-07-19T13:21:54.04-0400 [APP/PROC/WEB/0] ERR main.handleCommand(0xc420012240, 0xc42026c140, 0x4, 0x4, 0xc4206c05a0, 0xc420edb1e0)
   2018-07-19T13:21:54.05-0400 [APP/PROC/WEB/0] ERR 	/tmp/gobuildpack.gopath548464076/.go/src/supportBot/slackParse.go:185 +0x350
   2018-07-19T13:21:54.05-0400 [APP/PROC/WEB/0] ERR main.parse(0xc420012240, 0xc420b9fc90, 0x1)
   2018-07-19T13:21:54.05-0400 [APP/PROC/WEB/0] ERR 	/tmp/gobuildpack.gopath548464076/.go/src/supportBot/slackParse.go:58 +0x2f2
   2018-07-19T13:21:54.05-0400 [APP/PROC/WEB/0] ERR main.main()
   2018-07-19T13:21:54.05-0400 [APP/PROC/WEB/0] ERR 	/tmp/gobuildpack.gopath548464076/.go/src/supportBot/supportBot.go:103 +0x68b
~~~

**Comment by Tylarb** [comment]
Suggested fix - print error message if error returned from API call is 'channel_not_found'
